---
title: "Exclusion experiment trial report"
output: html_document
params:
  experiment: "."
  experiment_network_stats: "."
  D_combs: "."
---


<style type="text/css">
.main-container {
  max-width: 100% !important;
  margin: auto;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(spatstat)
library(igraph)
library(brainGraph)
library(patchwork)
library(ggrepel)
library(RColorBrewer)
library(knitr)
library(patchwork)

source("Model_code.R")

experiment <- params$experiment
experiment_network_stats <- params$experiment_network_stats
```

```{r}
# Simulation report plots --------------------------------------------------------

plot_nest_sizes <- function(experiment) {
  # Binding nest data
  nest_data <-
    bind_rows(
      # experiment$networks$control$nest_list |>
      #   mutate(experiment = "Control"),
      experiment$networks$strongest_re$nest_list |>
        mutate(experiment = "Strongest exclusion with reintroduction") |>
        mutate(Reintroduction = "Reintroduced") |>
        mutate(Exclusion = "Strongest"),
      experiment$networks$strongest_sus$nest_list |>
        mutate(experiment = "Strongest exclusion - sustained") |>
        mutate(Reintroduction = "Sustained") |>
        mutate(Exclusion = "Strongest"),
      
      experiment$networks$random_re$nest_list |>
        mutate(experiment = "Random exclusion with reintroduction") |>
        mutate(Reintroduction = "Reintroduced") |>
        mutate(Exclusion = "Random"),
      experiment$networks$random_sus$nest_list |>
        mutate(experiment = "Random exclusion - sustained") |>
        mutate(Reintroduction = "Sustained") |>
        mutate(Exclusion = "Random"),
      
      experiment$networks$weakest_re$nest_list |>
        mutate(experiment = "Weakest exclusion with reintroduction") |>
        mutate(Reintroduction = "Reintroduced") |>
        mutate(Exclusion = "Weakest"),
      experiment$networks$weakest_sus$nest_list |>
        mutate(experiment = "Weakest exclusion - sustained") |>
        mutate(Reintroduction = "Sustained") |>
        mutate(Exclusion = "Weakest")
    ) |>
    mutate(
      Reintroduction = factor(Reintroduction, levels = c("Reintroduced", "Sustained")),
      Exclusion = factor(Exclusion, levels = c("Weakest", "Random", "Strongest"))
    )
  
  # Rejoin data
  rejoin <-
    experiment$exclusion_info$rejoin |>
    mutate(experiment = factor(treatment, levels = c("weakest","random", "strongest" ))) |>
    mutate(
      experiment = recode_factor(
        experiment,
        `strongest` =
          "Strongest exclusion with reintroduction",
        
        `weakest` =
          "Weakest exclusion with reintroduction",
        
        `random` =
          "Random exclusion with reintroduction"
      )
    ) |>
    left_join(
      nest_data |>
        dplyr::select(ID, nest_size, t, experiment, Reintroduction, Exclusion),
      by = c(
        "t" = "t",
        "from_ID" = "ID",
        "experiment" = "experiment"
      )
    )
  
  # Affected nests
  affected_nests <-
    experiment$exclusion_info$affected_trails |>
    mutate(
      exclusion_category = str_to_title(exclusion_category),
      Exclusion = factor(
        exclusion_category,
        levels = c("Weakest", "Random", "Strongest")
      ),
      affected = "Directly affected"
    )
  
  nest_data <-
    nest_data |>
    left_join(
      affected_nests |>
        dplyr::select(from_ID, Exclusion, affected),
      by = c("ID" = "from_ID", "Exclusion")
    ) |>
    mutate(affected = as.factor(replace_na(affected, "Not directly affected")))
  
  
  # Terminal nest sizes for labels
  end_nest_size <-
    nest_data |>
    filter(status == "active") |>
    group_by(experiment, ID) |>
    summarise(end_t = max(t)) |>
    left_join(
      nest_data |>
        dplyr::select(ID, nest_size, t, experiment, Reintroduction, Exclusion),
      by = c(
        "end_t" = "t",
        "ID" = "ID",
        "experiment" = "experiment"
      )
    ) |>
    mutate(
      affected_nest = ifelse(
        ID %in% affected_nests,
        "Directly affected",
        "Not directly affected"
      )
    )
  
  # Preparing nest colour palette
  nest_IDs <-
    c(nest_data$ID) |> unique()
  
  nest_palette <-
    colorRampPalette(brewer.pal(8, "Paired"))(length(nest_IDs))
  
  names(nest_palette) <- nest_IDs
  
  # Plot
  exclusion_nest_size_plot <-
    nest_data |>
    filter(status == "active") |>
    ggplot(aes(
      y = nest_size,
      x = t,
      group = ID,
      colour = ID
    )) +
    facet_grid(rows = vars(Reintroduction),
               cols = vars(Exclusion)) +
    # Seasons
    geom_vline(xintercept = c(28, 56),
               colour = "blue") +
    
    # Lines
    geom_line(aes(linetype = affected)) +
    
    # Endpoints
    geom_point(data = end_nest_size,
               aes(y = nest_size,
                   x = end_t,
                   colour = ID)) +
    
    # Endpoint labels
    geom_label_repel(
      data = end_nest_size,
      aes(
        y = nest_size,
        x = end_t,
        colour = ID,
        label = ID
      ),
      alpha = 0.7,
      max.overlaps = Inf
    ) +
    
    # Did the excluded tree rejoin?
    geom_point(
      data = rejoin,
      aes(x = t,
          y = nest_size),
      colour = rep("magenta3", nrow(rejoin)),
      size = 4,
      shape = 18,
      alpha = 0.7,
      inherit.aes = FALSE
    ) +
    
    # Styling
    ylab("Nest size (1000 ants)") +
    scale_x_continuous(
      breaks = seq(from = 0, to = 84, by = 28),
      minor_breaks = seq(from = 0, to = 84, by = 14)
    ) +
    scale_linetype_manual(values = c(2, 1), name = "") +
    scale_colour_manual(values = nest_palette , guide = "none") +
    theme_bw() +
    theme(
      legend.position = "bottom",
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      strip.background = element_rect(fill = "white"),
      strip.text = element_text(face = "bold")
    )
  
  # Control plot
  end_nest_size_control <-
    experiment$networks$control$nest_list |>
    filter(status == "active") |>
    group_by(ID) |>
    summarise(end_t = max(t)) |> 
    left_join(
      experiment$networks$control$nest_list |>
        dplyr::select(ID, nest_size, t),
      by = c(
        "end_t" = "t",
        "ID" = "ID"
      )
    )
  
  control_nest_size_plot <-
    experiment$networks$control$nest_list |>
    filter(status == "active") |>
    mutate(Exclusion="Control") |> 
    ggplot(aes(
      y = nest_size,
      x = t,
      group = ID,
      colour = ID
    )) +
    facet_grid(cols = vars(Exclusion)) +
    # Seasons
    geom_vline(xintercept = c(28, 56),
               colour = "blue") +
    
    # Lines
    geom_line() +
    
    # Endpoints
    geom_point(data = end_nest_size_control,
               aes(y = nest_size,
                   x = end_t,
                   colour = ID)) +
    
    # Endpoint labels
    geom_label_repel(
      data = end_nest_size_control,
      aes(
        y = nest_size,
        x = end_t,
        colour = ID,
        label = ID
      ),
      alpha = 0.7,
      max.overlaps = Inf
    ) +
    
    # Styling
    ylab("Nest size (1000 ants)") +
    scale_x_continuous(
      breaks = seq(from = 0, to = 84, by = 28),
      minor_breaks = seq(from = 0, to = 84, by = 14)
    ) +
    scale_linetype_manual(values = c(2, 1), name = "") +
    scale_colour_manual(values = nest_palette , guide = "none") +
    theme_bw() +
    theme(
      legend.position = "bottom",
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      strip.background = element_rect(fill = "white"),
      strip.text = element_text(face = "bold")
    )
  
  layout <- "
AAA#
AAAB
"
  
  nest_size_plot <- 
    exclusion_nest_size_plot+
    control_nest_size_plot+
    plot_layout(#guides = 'collect',
      design = layout)
  
  return(nest_size_plot)
}

plot_trail_data <- function(experiment) {
  # Preparing nest colour palette
  trail_IDs <-
    bind_rows(
      experiment$networks$control$trail_list,
      experiment$networks$strongest_re$trail_list,
      experiment$networks$strongest_sus$trail_list,
      experiment$networks$weakest_re$trail_list,
      experiment$networks$weakest_sus$trail_list,
      experiment$networks$random_re$trail_list,
      experiment$networks$random_sus$trail_list
    ) |>
    mutate(trail_ID = paste(from_ID, to_ID)) |>
    pull(trail_ID) |>
    unique() |>
    sort()
  
  trail_palette <-
    colorRampPalette(brewer.pal(8, "Paired"))(length(trail_IDs))
  
  names(trail_palette) <- trail_IDs
  
  
  
  # Affected nests
  affected_nests <-
    experiment$exclusion_info$affected_trails |>
    mutate(
      exclusion_category = str_to_title(exclusion_category),
      Exclusion = factor(
        exclusion_category,
        levels = c("Weakest", "Random", "Strongest")
      ),
      affected = "Directly affected"
    )
  
  # Trail data
  trail_data <-
    bind_rows(
      # experiment$networks$control$trail_list |>
      #   mutate(experiment = "Control"),
      experiment$networks$strongest_re$trail_list |>
        mutate(experiment = "Strongest exclusion with reintroduction") |>
        mutate(Reintroduction = "Reintroduced") |>
        mutate(Exclusion = "Strongest"),
      experiment$networks$strongest_sus$trail_list |>
        mutate(experiment = "Strongest exclusion - sustained") |>
        mutate(Reintroduction = "Sustained") |>
        mutate(Exclusion = "Strongest"),
      
      experiment$networks$random_re$trail_list |>
        mutate(experiment = "Random exclusion with reintroduction") |>
        mutate(Reintroduction = "Reintroduced") |>
        mutate(Exclusion = "Random"),
      experiment$networks$random_sus$trail_list |>
        mutate(experiment = "Random exclusion - sustained") |>
        mutate(Reintroduction = "Sustained") |>
        mutate(Exclusion = "Random"),
      
      experiment$networks$weakest_re$trail_list |>
        mutate(experiment = "Weakest exclusion with reintroduction") |>
        mutate(Reintroduction = "Reintroduced") |>
        mutate(Exclusion = "Weakest"),
      experiment$networks$weakest_sus$trail_list |>
        mutate(experiment = "Weakest exclusion - sustained") |>
        mutate(Reintroduction = "Sustained") |>
        mutate(Exclusion = "Weakest")
    ) |>
    mutate(
      Reintroduction = factor(Reintroduction, levels = c("Reintroduced", "Sustained")),
      Exclusion = factor(Exclusion, levels = c("Weakest", "Random", "Strongest")),
      trail_ID = paste(from_ID, to_ID)
    ) |>
    left_join(
      affected_nests |>
        dplyr::select(from_ID, Exclusion, affected),
      by = c("from_ID" = "from_ID", "Exclusion")
    ) |>
    mutate(affected = as.factor(replace_na(affected, "Not directly affected")))
  
  # Rejoin data
  rejoin <-
    experiment$exclusion_info$rejoin |>
    mutate(experiment = factor(treatment, levels = c("weakest","random", "strongest"))) |>
    mutate(
      Exclusion = recode_factor(
        experiment,
        `strongest` =
          "Strongest",
        
        `weakest` =
          "Weakest",
        
        `random` =
          "Random"
      ),
      Reintroduction = "Reintroduced"
    )
  
  # Terminal trail strengths for labels
  end_strength <-
    trail_data |>
    filter(status == "active") |>
    group_by(experiment, trail_ID) |>
    summarise(end_t = max(t)) |>
    left_join(
      trail_data |>
        dplyr::select(
          trail_ID,
          from_ID,
          strength,
          t,
          experiment,
          Reintroduction,
          Exclusion
        ),
      by = c(
        "end_t" = "t",
        "trail_ID" = "trail_ID",
        "experiment" = "experiment"
      )
    ) |>
    mutate(
      affected_nest = ifelse(
        from_ID %in% affected_nests,
        "Directly affected",
        "Not directly affected"
      )
    )
  
  # Plot
  exclusion_trail_data_plot <-
    trail_data |>
    filter(status == "active")  |>
    ggplot(aes(
      x = t,
      y = strength,
      group = trail_ID,
      colour = trail_ID
    )) +
    facet_grid(rows = vars(Reintroduction),
               cols = vars(Exclusion)) +
    # Seasons
    geom_vline(xintercept = c(28, 56),
               colour = "blue") +
    # Lines
    geom_line(aes(linetype = affected,
                  linewidth = trail_type)) +
    
    # Endpoint labels
    geom_text_repel(
      data = end_strength,
      aes(
        y = strength,
        x = end_t,
        colour = trail_ID,
        label = trail_ID
      ),
      alpha = 0.7,
      max.overlaps = Inf
    ) +
    
    # Did the excluded tree rejoin?
    geom_point(
      data = rejoin,
      aes(x = t,
          y = strength),
      colour = rep("magenta3", nrow(rejoin)),
      size = 4,
      shape = 18,
      alpha = 0.7,
      inherit.aes = FALSE
    ) +
    
    # Styling
    ylab("Trail strength (ants/mm)") +
    scale_linewidth_ordinal(range = c(0, 1.3), name = "") +
    scale_colour_manual(values = trail_palette , guide = "none") +
    scale_linetype_manual(values = c(2, 1), name = "Trail type") +
    scale_x_continuous(
      breaks = seq(from = 0, to = 84, by = 28),
      minor_breaks = seq(from = 0, to = 84, by = 14)
    ) +
    theme_bw() +
    theme(
      legend.position = "bottom",
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      strip.background = element_rect(fill = "white"),
      strip.text = element_text(face = "bold")
    )
  
  
  # Terminal trail strengths for labels - control
  end_strength_control <-
    experiment$networks$control$trail_list |>
    filter(status == "active")  |>
    mutate(trail_ID = paste(from_ID, to_ID),
           Exclusion = "Control") |>
    group_by(trail_ID) |>
    summarise(end_t = max(t)) |>
    left_join(
      experiment$networks$control$trail_list |>
        filter(status == "active")  |>
        mutate(trail_ID = paste(from_ID, to_ID),
               Exclusion = "Control") |>
        dplyr::select(trail_ID, t,  strength),
      by = c("end_t" = "t",
             "trail_ID" = "trail_ID")
    )
  
  # Control plot
  control_trail_data_plot <-
    experiment$networks$control$trail_list |>
    filter(status == "active")  |>
    mutate(trail_ID = paste(from_ID, to_ID),
           Exclusion = "Control") |>
    ggplot(aes(
      x = t,
      y = strength,
      group = trail_ID,
      colour = trail_ID
    )) +
    facet_grid(cols = vars(Exclusion)) +
    # Seasons
    geom_vline(xintercept = c(28, 56),
               colour = "blue") +
    # Lines
    geom_line(aes(linewidth = trail_type)) +
    
    # Endpoint labels
    geom_text_repel(
      data = end_strength_control,
      aes(
        y = strength,
        x = end_t,
        colour = trail_ID,
        label = trail_ID
      ),
      alpha = 0.7,
      max.overlaps = Inf
    ) +
    
    # Styling
    ylab("Trail strength (ants/mm)") +
    scale_linewidth_ordinal(range = c(0, 1.3), name = "Trail type") +
    scale_colour_manual(values = trail_palette , guide = "none") +
    
    scale_x_continuous(
      breaks = seq(from = 0, to = 84, by = 28),
      minor_breaks = seq(from = 0, to = 84, by = 14)
    ) +
    theme_bw() +
    theme(
      legend.position = "bottom",
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      strip.background = element_rect(fill = "white"),
      strip.text = element_text(face = "bold")
    )
  
  layout <- "
AAA#
AAAB
"
  
  trail_data_plot <-
    exclusion_trail_data_plot +
    control_trail_data_plot +
    plot_layout(#guides = 'collect',
      design = layout)
  
  return(trail_data_plot)
}




plot_networks <- function(experiment,
                          time_steps = c(
                            (-not_estimated_parameters$burn_in_length),
                            0, 28, 56, 84)) {
  # Affected nests
  affected_nests <-
    experiment$exclusion_info$affected_trails |>
    mutate(
      exclusion_category = str_to_title(exclusion_category),
      Exclusion = factor(
        exclusion_category,
        levels = c("Weakest", "Random", "Strongest")
      ),
      affected = "Directly affected"
    )
  
  # Excluded trees
  excluded_trees <-
    experiment$exclusion_info$affected_trails |>
    mutate(
      exclusion_category = str_to_title(exclusion_category),
      Exclusion = factor(
        exclusion_category,
        levels = c("Weakest", "Random", "Strongest")
      ),
      excluded = "Excluded"
    ) |>
    select(to_ID, Exclusion, excluded) |>
    group_by(Exclusion) |>
    unique()
  
  nest_data <-
    bind_rows(
      experiment$networks$control$nest_list |>
        mutate(experiment = "Control",
               Exclusion = "Control"),
      
      experiment$networks$strongest_re$nest_list |>
        mutate(experiment = "Strongest exclusion:\nreintroduction",
               Exclusion = "Strongest") ,
      experiment$networks$strongest_sus$nest_list |>
        mutate(experiment = "Strongest exclusion:\nsustained",
               Exclusion = "Strongest") ,
      
      experiment$networks$random_re$nest_list |>
        mutate(experiment = "Random exclusion:\nreintroduction",
               Exclusion = "Random") ,
      experiment$networks$random_sus$nest_list |>
        mutate(experiment = "Random exclusion:\nsustained",
               Exclusion = "Random") ,
      
      experiment$networks$weakest_re$nest_list |>
        mutate(experiment = "Weakest exclusion:\nreintroduction",
               Exclusion = "Weakest") ,
      experiment$networks$weakest_sus$nest_list |>
        mutate(experiment = "Weakest exclusion:\nsustained",
               Exclusion = "Weakest")
    ) |>
    left_join(
      affected_nests |>
        dplyr::select(from_ID, Exclusion, affected),
      by = c("ID" = "from_ID", "Exclusion")
    ) |>
    mutate(
      affected = as.factor(replace_na(affected, "Not directly affected")),
      experiment = factor(experiment,
                          levels = unique(experiment)[c(1, 7, 6, 5, 4, 3, 2)])
    )
  
  
  tree_data <-
    bind_rows(
      experiment$networks$control$tree_list |>
        mutate(experiment = "Control",
               Exclusion = "Control"),
      
      experiment$networks$strongest_re$tree_list |>
        mutate(experiment = "Strongest exclusion:\nreintroduction",
               Exclusion = "Strongest") ,
      experiment$networks$strongest_sus$tree_list |>
        mutate(experiment = "Strongest exclusion:\nsustained",
               Exclusion = "Strongest") ,
      
      experiment$networks$random_re$tree_list |>
        mutate(experiment = "Random exclusion:\nreintroduction",
               Exclusion = "Random") ,
      experiment$networks$random_sus$tree_list |>
        mutate(experiment = "Random exclusion:\nsustained",
               Exclusion = "Random") ,
      
      experiment$networks$weakest_re$tree_list |>
        mutate(experiment = "Weakest exclusion:\nreintroduction",
               Exclusion = "Weakest") ,
      experiment$networks$weakest_sus$tree_list |>
        mutate(experiment = "Weakest exclusion:\nsustained",
               Exclusion = "Weakest")
    ) |>
    left_join(excluded_trees,
              by = c("ID" = "to_ID", "Exclusion" = "Exclusion")) |>
    mutate(
      excluded = as.factor(replace_na(excluded, "Not excluded")),
      experiment = factor(experiment,
                          levels = unique(experiment)[c(1, 7, 6, 5, 4, 3, 2)])
    )
  
  inactive_trees <-
    tree_data |>
    filter(t %in% time_steps,
           excluded == "Excluded",
           status == "abandoned") |>
    mutate(t = paste0("t = ", t))
  
  trail_data <-
    bind_rows(
      experiment$networks$control$trail_list |>
        mutate(experiment = "Control"),
      
      experiment$networks$strongest_re$trail_list |>
        mutate(experiment = "Strongest exclusion:\nreintroduction") ,
      experiment$networks$strongest_sus$trail_list |>
        mutate(experiment = "Strongest exclusion:\nsustained") ,
      
      experiment$networks$random_re$trail_list |>
        mutate(experiment = "Random exclusion:\nreintroduction") ,
      experiment$networks$random_sus$trail_list |>
        mutate(experiment = "Random exclusion:\nsustained") ,
      
      experiment$networks$weakest_re$trail_list |>
        mutate(experiment = "Weakest exclusion:\nreintroduction") ,
      experiment$networks$weakest_sus$trail_list |>
        mutate(experiment = "Weakest exclusion:\nsustained")
    ) |>
    mutate(experiment = factor(
      experiment, levels = unique(experiment)[c(1, 7, 6, 5, 4, 3, 2)])
    )
  
  tree_labels <-
    trail_data |>
    filter(trail_type == "foraging") |>
    select(to_ID, to_y, to_x) |>
    unique()
  
  
  # Plot boundaries
  min_x <-
    min(c(
      c(trail_data[, c("from_x", "to_x")]),
      c(experiment$control$trail_list[, c("from_x", "to_x")]),
      recursive = T
    )) * 1.01
  
  max_x <-
    max(c(
      c(trail_data[, c("from_x", "to_x")]),
      c(experiment$control$trail_list[, c("from_x", "to_x")]),
      recursive = T
    )) * 1.01
  
  min_y <-
    min(c(
      c(trail_data[, c("from_y", "to_y")]),
      c(experiment$control$trail_list[, c("from_y", "to_y")]),
      recursive = T
    )) * 1.01
  
  max_y <-
    max(c(
      c(trail_data[, c("from_y", "to_y")]),
      c(experiment$control$trail_list[, c("from_y", "to_y")]),
      recursive = T
    )) * 1.01
  
  max_strength <-
    ceiling(max(c(trail_data[, "strength"],
                  trail_data[, "strength"])) * 10) / 10
  # Plot
  network_maps <-
    ggplot() +
    # Trails
    geom_segment(
      data = trail_data |>
        filter(t %in% time_steps) |>
        filter(status == "active") |>
        mutate(t = paste0("t = ", t)),
      aes(
        x = from_x,
        y = from_y,
        xend = to_x,
        yend = to_y,
        colour = trail_type,
        linewidth = strength
      ),
      alpha = 0.7
    ) +
    # Trees
    geom_point(
      data = tree_data |>
        filter(t %in% time_steps) |>
        mutate(t = paste0("t = ", t)),
      aes(x = x,
          y = y,
          shape = excluded),
      fill = "forestgreen",
      colour = "black",
      size = 2
    ) +
    facet_grid(cols = vars(experiment),
               rows = vars(t)) +
    
    # Nests
    geom_point(
      data = nest_data |>
        filter(status == "active",
               t %in% time_steps) |>
        mutate(t = paste0("t = ", t)),
      aes(
        x = x,
        y = y,
        size = nest_size,
        fill = affected
      ),
      colour = "black",
      pch = 21,
      alpha = 0.6
    ) +
    facet_grid(cols = vars(experiment),
               rows = vars(t)) +
    
    # Inactive trees
    geom_point(
      data = inactive_trees,
      aes(x = x,
          y = y),
      colour = "magenta3",
      alpha = 0.3,
      size = 5,
      shape = 16
    ) +
    
    # Tree labels
    geom_text_repel(data = tree_labels,
                    aes(x = to_x,
                        y = to_y,
                        label = to_ID),
                    colour = "forestgreen",
                    max.overlaps = Inf) +
    # Nest labels
    geom_text_repel(
      data = nest_data |>
        filter(status == "active",
               t %in% time_steps) |>
        mutate(t = paste0("t = ", t)),
      aes(x = x,
          y = y,
          label = ID),
      colour = "black",
      max.overlaps = Inf
    ) +
    
    # Scaling
    ylim(min_y, max_y) +
    xlim(min_x, max_x) +
    ylab("y (m)") +
    xlab("x (m)") +
    
    # Styling
    scale_colour_manual(
      values = c("forestgreen", "black", "black", "forestgreen"),
      name = "Trail type",
      labels = c("internest trail", "foraging trail")
    ) +
    scale_linewidth_continuous(limits = c(0, max_strength),
                               name = "Trail strength (ants/mm)") +
    scale_size_continuous(limits = c(0, ceiling(not_estimated_parameters$K /
                                                  10) * 10),
                          name = "Nest size (1000 ants)") +
    scale_fill_manual(values = c("dodgerblue", "black"),
                      name = "Nest by exclusion") +
    scale_shape_manual(values = c(25, 21), "Tree") +
    
    theme_bw() +
    theme(
      panel.grid = element_blank(),
      aspect.ratio = 1,
      legend.position = "bottom",
      strip.background = element_rect(fill = "white"),
      strip.text = element_text(face = "bold"),
      axis.title = element_text(face =  "bold")
    ) +
    guides(
      size=guide_legend(title.position = "top",
                        # title.hjust = 0.5,
                        order=3, nrow = 1,
                        label.position = "bottom",
                        title.theme = element_text(face = "bold")),
      linewidth=guide_legend(title.position = "top",
                             # title.hjust = 0.5,
                             order=5, nrow = 1,
                             label.position = "bottom",
                             title.theme = element_text(face = "bold")),
      shape=guide_legend(title.position = "top",
                         #title.hjust = 0.5,
                         order=1, ncol = 1,
                         title.theme = element_text(face = "bold")),
      fill=guide_legend(title.position = "top",
                        #title.hjust = 0.5,
                        order=2, ncol = 1,
                        title.theme = element_text(face = "bold")),
      colour=guide_legend(title.position = "top",
                          #title.hjust = 0.5,
                          order=4, ncol = 1,
                          title.theme = element_text(face = "bold")),)
  
  return(network_maps)
  
}

plot_network_stats <- function(experiment_network_stats) {
  treatment_keys <- data.frame(
    treatment = c(
      "control",
      "strongest_re",
      "strongest_sus",
      "weakest_re",
      "weakest_sus",
      "random_re",
      "random_sus"
    ),
    Reintroduction = factor(
      c(
        "Control",
        "Reintroduced",
        "Sustained",
        "Reintroduced",
        "Sustained",
        "Reintroduced",
        "Sustained"
      ),
      levels = c("Control", "Sustained", "Reintroduced")
    ),
    Exclusion = factor(
      c(
        "Control",
        "Strongest",
        "Strongest",
        "Weakest",
        "Weakest",
        "Random",
        "Random"
      ),
      levels = c("Control", "Weakest", "Random", "Strongest")
    )
  )
  
  stat_names  <-  c(
    "Number of nests",
    "Number of trees",
    "Number of\nforaging trails",
    "Number of\ninternest trail",
    "Trees to\nnests ratio",
    "Internest\nto nests ratio",
    "Foraging\nto nests ratio",
    "Number of components -\ninternest only",
    "Edge density",
    "Edge density -\ninternest only",
    "Network efficiency",
    "Network efficiency -\ninternest only",
    "Network robustness",
    "Network robustness -\ninternest only",
    "Network cost",
    "Network cost -\ninternest only",
    "Resource capital",
    "Resource variance",
    "Dissimilarity to t=0 (D)",
    "Dissimilarity to t=0 (D) -\ninternest only"
  )
  
  stat_keys <-
    data.frame(
      stat = c(
        "num_nests",
        "num_trees",
        "num_foraging",
        "num_internest",
        "trees_to_nests_rat",
        "internest_to_nests_rat",
        "foraging_to_nests_rat",
        "num_components_nests",
        "edge_density",
        "edge_density_nests",
        "network_efficiency",
        "network_efficiency_nests",
        "network_robustness",
        "network_robustness_nests",
        "network_cost",
        "network_cost_nests",
        "resource_capital",
        "resource_variance",
        "D_with_t_0",
        "D_with_t_0_nests"
      ),
      stat_keys = factor(stat_names, levels = stat_names)
    )
  
  
  experiment_network_stats_plot <-
    experiment_network_stats |>
    pivot_longer(-c(t, treatment), names_to = "stat", values_to = "stat_value") |>
    filter(!((stat %in% c("resource_capital","resource_variance"))&t<0)) |> 
    left_join(treatment_keys, by = "treatment") |>
    left_join(stat_keys, by = "stat") |>
    ggplot(
      aes(
        x = t,
        y = stat_value,
        group = treatment,
        colour = Exclusion,
        linetype = Reintroduction
      )
    ) +
    facet_wrap(vars(stat_keys), scales = "free_y") +
    geom_line(position = position_dodge(width = 5)) +
    #geom_line()+
    #geom_point()+
    scale_colour_manual(values = c("black", "skyblue1", "purple", "red")) +
    scale_linetype_manual(values = c("solid", "solid", "dashed")) +
    scale_x_continuous(
      breaks = seq(from = 0, to = 84, by = 28),
      minor_breaks = seq(from = 0, to = 84, by = 14)
    ) +
    ylab("") +
    theme_bw() +
    theme(
      legend.position = "right",
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      strip.background = element_rect(fill = "white"),
      strip.text = element_text(face = "bold")
    )
  
  return(experiment_network_stats_plot)
  
}


# Variable names for plotting ---------------------------------------------
stat_names  <-  c(
  "Number of nests",
  "Number of trees",
  "Number of\nforaging trails",
  "Number of\ninternest trail",
  "Trees to\nnests ratio",
  "Internest\nto nests ratio",
  "Foraging\nto nests ratio",
  "Number of components -\ninternest only",
  "Edge density",
  "Edge density -\ninternest only",
  "Network efficiency",
  "Network efficiency -\ninternest only",
  "Network robustness",
  "Network robustness -\ninternest only",
  "Network cost",
  "Network cost -\ninternest only",
  "Resource capital",
  "Resource variance",
  "Dissimilarity to t=0 (D)",
  "Dissimilarity to t=0 (D) -\ninternest only"
)


stat_keys <-
  data.frame(
    stat = c(
      "num_nests",
      "num_trees",
      "num_foraging",
      "num_internest",
      "trees_to_nests_rat",
      "internest_to_nests_rat",
      "foraging_to_nests_rat",
      "num_components_nests",
      "edge_density",
      "edge_density_nests",
      "network_efficiency",
      "network_efficiency_nests",
      "network_robustness",
      "network_robustness_nests",
      "network_cost",
      "network_cost_nests",
      "resource_capital",
      "resource_variance",
      "D_with_t_0",
      "D_with_t_0_nests"
    ),
    stat_keys = factor(stat_names, levels = stat_names)
  )


treatment_keys  <-  data.frame(
  treatment = factor(
    c(
      "control",
      "strongest_re",
      "strongest_sus",
      "weakest_re",
      "weakest_sus",
      "random_re",
      "random_sus"
    ),
    levels = c(
      "control",
      "strongest_re",
      "strongest_sus",
      "weakest_re",
      "weakest_sus",
      "random_re",
      "random_sus"
    )
  )
    ,
  Exclusion =
    factor(
      c(
        "Control",
        "Strongest",
        "Strongest",
        "Weakest",
        "Weakest",
        "Random",
        "Random"
      ),
      levels = c("Control", "Weakest", "Random", "Strongest")
    ),
  Reintroduction =
    factor(
      c(
        "Control",
        "Reintroduced",
        "Sustained",
        "Reintroduced",
        "Sustained",
        "Reintroduced",
        "Sustained"
      ),
      levels = c("Control", "Sustained", "Reintroduced")
    )
)


treatment_combs <-
  combn(as.character(treatment_keys$treatment), 2) |>
  t() |>
  as.data.frame() |>
  tibble() |>
  rename(Treatment1 = V1, Treatment2 = V2) |>
  mutate(
    Treatment1 = factor(
      Treatment1,
      levels = c(
        "control",
        "weakest_sus",
        "weakest_re",
        "random_sus",
        "random_re",
        "strongest_sus",
        "strongest_re"
      )
    ),
    Treatment2 = factor(
      Treatment2,
      levels = c(
        "control",
        "weakest_sus",
        "weakest_re",
        "random_sus",
        "random_re",
        "strongest_sus",
        "strongest_re"
      )
    )
  )
```

```{r Preparing plots, include=FALSE}


nest_sizes_plot <- plot_nest_sizes(experiment)
trail_data_plot <- plot_trail_data(experiment)
networks_plot <- plot_networks(experiment)
network_stats_plot <- plot_network_stats(experiment_network_stats)

stat_names  <-  c(
    "Number of nests",
    "Number of trees",
    "Number of foraging trails",
    "Number of internest trail",
    "Trees to nests ratio",
    "Internest to nests ratio",
    "Foraging to nests ratio",
    "Number of components - internest only",
    "Edge density",
    "Edge density - internest only",
    "Network efficiency",
    "Network efficiency - internest only",
    "Network robustness",
    "Network robustness - internest only",
    "Network cost",
    "Network cost - internest only"
  )
colnames(experiment_network_stats)[3:length(colnames(experiment_network_stats))] <- stat_names


```

# Exclusion info
```{r}
# Exclusion info
experiment$exclusion_info$affected_trails |> 
  mutate(exclusion_category=factor(exclusion_category, levels=c("strongest","random","weakest"))) |> 
  arrange(exclusion_category) |> 
  select(exclusion_category,from_ID,to_ID,strength) |> 
  kable(col.names = c("Exclusion category","Nest","Tree","Trail strength (ants/mm)"),
        digits = c(2),
        caption = "Trees and associated foraging trails excluded in different treatment groups")

```



```{r rejoin table}
# Did the excluded tree rejoin the network in the reintroduction groups?
experiment$exclusion_info$rejoin |> 
  select(treatment,t,from_ID,to_ID) |> 
  kable(col.names = c("Exclusion treatment group","Time of rejoin","Nest","Tree"),
       #format = "html", table.attr = "style='width:30%;'",
       caption = "Trees in reintroduction groups that rejoined the network")

```

# Nest sizes
```{r nest size plot, fig.height=10, fig.width=15}
nest_sizes_plot
```

# Trail strengths
```{r trail strength plot, fig.height=10, fig.width=15}
trail_data_plot
```

# Network maps
```{r network map plot, fig.height=15, fig.width=20, message=FALSE, warning=FALSE}
networks_plot
```

# Network statistics plot
```{r network stats plot, fig.height=10, fig.width=15, warning=FALSE}
network_stats_plot
```

# Network statistics
```{r network stats table}
experiment_network_stats |> 
  kable(digits = 2)

```

